language: ruby
rvm:
- 2.2.5

before_script:
 - chmod +x ./script/deploy.sh

script: bash ./script/deploy.sh

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: "nimius.rd@gmail.com"
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"

sudo: false

after_success:
