language: ruby, node_js
cache: bundler
rvm:
- 2.3.1

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache

branches:
  only:
    - gh-pages
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    - JEKYLL_ENV: "production"
    - SOURCE_BRANCH: "master"
    - TARGET_BRANCH: "gh-pages"
    - COMMIT_AUTHOR_EMAIL: "nimius.rd@gmail.com"
    - ENCRYPTION_LABEL: 42792a9386ff

before_script:
  - chmod -vR +x tools

script:
  - npm run build
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
