language: ruby
rvm:
- 2.2.2
sudo: false
cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - nvm install 7
  - npm i -g yarn
  - yarn

branches:
  only:
    - gh-pages
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    - JEKYLL_ENV: "production"
    - SOURCE_BRANCH: "master"
    - TARGET_BRANCH: "gh-pages"
    - COMMIT_AUTHOR_EMAIL: "nimius.rd@gmail.com"
    - ENCRYPTION_LABEL: 42792a9386ff

before_script:
  - chmod -vR +x tools/deploy.sh

script:
  - yarn build
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
  - ./tools/deploy.sh
