language: ruby
rvm:
- 2.2.5

before_script:
 - chmod +x ./script/deploy.sh

script: ./script/deploy.sh

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

after_success:
