language: node_js
rvm:
- 2.3.1
node_js:
  - "6"
sudo: false
cache:
  bundler: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - vendor/bundle

before_install:
  - rvm use 2.3.1 --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version
  - npm i -g yarn

install:
  - yarn
  - bundle install --jobs=3 --retry=3 --deployment --path vendor/bundle

branches:
  only:
    - gh-pages
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    - JEKYLL_ENV: "production"
    - SOURCE_BRANCH: "master"
    - TARGET_BRANCH: "gh-pages"
    - COMMIT_AUTHOR_EMAIL: "nimius.rd@gmail.com"
    - ENCRYPTION_LABEL: 42792a9386ff

before_script:
  - chmod -vR +x tools

script:
  - yarn build
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
