language: ruby
rvm:
- 2.2.5

branches:
  only:
  - gh-pages
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: "nimius.rd@gmail.com"
  - ENCRYPTION_LABEL: "42792a9386ff"

sudo: false

before_script:
  - chmod +x ./script/deploy.sh

script: bash ./script/deploy.sh
