language: ruby
cache: bundler
rvm:
- 2.2.5

branches:
  only:
    - gh-pages
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - SOURCE_BRANCH: "master"
    - TARGET_BRANCH: "gh-pages"
    - COMMIT_AUTHOR_EMAIL: "nimius.rd@gmail.com"
    - ENCRYPTION_LABEL: 42792a9386ff

sudo: false

before_script:
  - pwd
  - chmod +x $/tools

script:
  - ./tools/build.sh
  - ./tools/test.sh
  - ./tools/deploy.sh
