source: ./src
destination: ./_site
markdown: kramdown
exclude: [vendor, deploy_key]
gems: ['jekyll-github-metadata']
repository: nimiusrd/hp

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
