source: ./src
destination: ./_site/hp
baseurl: /hp
markdown: kramdown
exclude:
  - vendor
  - deploy_key
  - entry.js
  - css
gems:
  - 'jekyll-github-metadata'
repository: nimiusrd/hp
permalink: /post/:title.html
